/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as EmployeesImport } from './routes/employees'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as EmployeesEmployeeIdImport } from './routes/employees/$employeeId'

// Create/Update Routes

const EmployeesRoute = EmployeesImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const EmployeesEmployeeIdRoute = EmployeesEmployeeIdImport.update({
  id: '/$employeeId',
  path: '/$employeeId',
  getParentRoute: () => EmployeesRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesImport
      parentRoute: typeof rootRoute
    }
    '/employees/$employeeId': {
      id: '/employees/$employeeId'
      path: '/$employeeId'
      fullPath: '/employees/$employeeId'
      preLoaderRoute: typeof EmployeesEmployeeIdImport
      parentRoute: typeof EmployeesImport
    }
  }
}

// Create and export the route tree

interface EmployeesRouteChildren {
  EmployeesEmployeeIdRoute: typeof EmployeesEmployeeIdRoute
}

const EmployeesRouteChildren: EmployeesRouteChildren = {
  EmployeesEmployeeIdRoute: EmployeesEmployeeIdRoute,
}

const EmployeesRouteWithChildren = EmployeesRoute._addFileChildren(
  EmployeesRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/employees': typeof EmployeesRouteWithChildren
  '/employees/$employeeId': typeof EmployeesEmployeeIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/employees': typeof EmployeesRouteWithChildren
  '/employees/$employeeId': typeof EmployeesEmployeeIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/employees': typeof EmployeesRouteWithChildren
  '/employees/$employeeId': typeof EmployeesEmployeeIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/employees' | '/employees/$employeeId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/employees' | '/employees/$employeeId'
  id: '__root__' | '/' | '/about' | '/employees' | '/employees/$employeeId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EmployeesRoute: typeof EmployeesRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EmployeesRoute: EmployeesRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/employees"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/employees": {
      "filePath": "employees.tsx",
      "children": [
        "/employees/$employeeId"
      ]
    },
    "/employees/$employeeId": {
      "filePath": "employees/$employeeId.tsx",
      "parent": "/employees"
    }
  }
}
ROUTE_MANIFEST_END */
